#! /bin/bash
######## Part 1 #########
# Script parameters     #
#########################
  
# Specify the partition name from which resources will be allocated, mandatory option
#SBATCH --partition=gpu
  
# Specify the QOS, mandatory option
#SBATCH --qos=normal
  
# Specify which group you belong to, mandatory option
# This is for the accounting, so if you belong to many group,
#SBATCH --account=junogpu
  
# Specify your job name, optional option, but strongly recommand to specify some name
#SBATCH --job-name=train_1
  
# Specify how many cores you will need, default is one if not specified
#SBATCH --ntasks=1
  
# Specify the output file path of your job
# Attention!! Your afs account must have write access to the path
# Or the job will be FAILED!
#SBATCH --output=/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/job_sub/jobs/testing_pi-.out
#SBATCH --error=/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/job_sub/jobs/testing_pi-.err
  
# Specify memory to use, or slurm will allocate all available memory in MB
#SBATCH --mem-per-cpu=30720
#SBATCH --cpus-per-task=2  
#
# Specify how many GPU cards to use
#SBATCH --gres=gpu:v100:1 
######## Part 2 ######
# Script workload    #
######################
  
# Replace the following lines with your real workload
  
# list the allocated hosts
echo CUDA_VISIBLE_DEVICES $CUDA_VISIBLE_DEVICES
hostname
df -h
cd /hpcfs/juno/junogpu/fangwx
source /hpcfs/juno/junogpu/fangwx/setup.sh


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch50.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch50.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch50.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch50.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch51.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch51.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch51.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch51.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch52.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch52.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch52.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch52.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch53.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch53.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch53.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch53.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch54.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch54.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch54.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch54.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch55.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch55.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch55.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch55.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch56.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch56.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch56.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch56.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch57.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch57.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch57.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch57.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch58.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch58.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch58.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch58.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch59.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch59.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch59.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch59.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch60.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch60.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch60.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch60.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch61.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch61.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch61.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch61.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch62.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch62.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch62.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch62.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch63.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch63.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch63.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch63.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch64.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch64.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch64.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch64.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch65.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch65.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch65.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch65.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch66.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch66.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch66.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch66.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch67.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch67.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch67.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch67.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch68.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch68.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch68.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch68.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch69.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch69.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch69.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch69.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch70.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch70.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch70.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch70.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch71.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch71.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch71.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch71.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch72.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch72.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch72.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch72.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch73.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch73.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch73.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch73.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch74.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch74.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch74.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch74.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch75.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch75.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch75.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch75.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch76.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch76.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch76.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch76.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch77.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch77.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch77.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch77.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch78.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch78.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch78.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch78.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch79.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch79.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch79.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch79.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch80.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch80.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch80.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch80.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch81.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch81.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch81.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch81.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch82.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch82.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch82.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch82.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch83.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch83.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch83.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch83.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch84.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch84.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch84.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch84.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch85.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch85.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch85.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch85.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch86.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch86.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch86.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch86.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch87.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch87.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch87.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch87.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch88.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch88.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch88.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch88.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch89.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch89.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch89.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch89.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch90.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch90.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch90.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch90.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch91.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch91.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch91.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch91.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch92.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch92.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch92.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch92.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch93.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch93.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch93.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch93.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch94.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch94.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch94.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch94.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch95.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch95.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch95.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch95.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch96.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch96.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch96.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch96.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch97.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch97.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch97.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch97.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch98.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch98.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch98.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch98.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 


/hpcfs/juno/junogpu/fangwx/python/Python-3.6.6/python /hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/generator_v7_EcalOnly.py --latent-size 512 --gen-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/gen_model_0306_epoch99.h5" --comb-model-in "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/comb_model_0306_epoch99.h5"   --exact-model False --exact-list ''  --output "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/Gen_fix_0306_epoch99.h5" --check-dis-real True --dis-model-in '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/params/gan/pi-_fix/dis_model_0306_epoch99.h5' --real-data '/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/data/HCAL/pi-_fix/HoEless2/h5/Digi_sim_10_pionm_94.h5' --convert2pb False --path_pb "/hpcfs/juno/junogpu/fangwx/FastSim/CEPC/generator/pi-/" --name_pb "model.pb" --SavedModel False 

